using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;
using System.Xml.Serialization;

namespace MVC_2020_Business.Models.Authenticus
{
        //------------------------------------------------------------------------------
    // <auto-generated>
    //     Este código foi gerado por uma ferramenta.
    //     Versão de Tempo de Execução:4.0.30319.42000
    //
    //     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
    //     o código for regenerado.
    // </auto-generated>
    //------------------------------------------------------------------------------


    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.authenticus.pt/api/v2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.authenticus.pt/api/v2.0", IsNullable=false)]
    public partial class publication {
        
        private publicationType[] typeField;
        
        private string titleField;
        
        private string subtitleField;
        
        private publicationAuthor[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private string yearField;
        
        private string abstractField;
        
        private string doiField;
        
        private string sourcetitleField;
        
        private string isosourceabbreviationField;
        
        private string charactersourceabbreviationField;
        
        private string dateField;
        
        private string issnField;
        
        private string volumeField;
        
        private string issueField;
        
        private string pagesField;
        
        private string pagescountField;
        
        private publicationReprintAddress[] reprintaddressField;
        
        private string bookdoiField;
        
        private string codenField;
        
        private publicationPublisher publisherField;
        
        private string languageField;
        
        private string[] emailField;
        
        private publicationConference conferenceField;
        
        private string isbnField;
        
        private string eisbnField;
        
        private string partnumberField;
        
        private string bookgroupauthorField;
        
        private string bookseriestitleField;
        
        private string supplementField;
        
        private string meetingabstractnumberField;
        
        private string[] groupauthorField;
        
        private string specialissueField;
        
        private string eissnField;
        
        private string articlenumberField;
        
        private publicationAuthor[] bookeditorField;
        
        private string[] keywordField;
        
        private string[] fieldField;
        
        private publicationAffiliation[] affiliationField;
        
        private publicationTimesCited[] timescitedField;
        
        private publicationExternalIdentifier[] externalidentifierField;
        
        private publicationMetadataSource[] metadatasourceField;
        
        private string idField;
        
        private string modifiedtimeField;
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("type")]
        public publicationType[] type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <observações/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <observações/>
        public string subtitle {
            get {
                return this.subtitleField;
            }
            set {
                this.subtitleField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("author", typeof(publicationAuthor))]
        [System.Xml.Serialization.XmlElementAttribute("editor", typeof(publicationAuthor))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public publicationAuthor[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <observações/>
        public string @abstract {
            get {
                return this.abstractField;
            }
            set {
                this.abstractField = value;
            }
        }
        
        /// <observações/>
        public string doi {
            get {
                return this.doiField;
            }
            set {
                this.doiField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("source-title")]
        public string sourcetitle {
            get {
                return this.sourcetitleField;
            }
            set {
                this.sourcetitleField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("iso-source-abbreviation")]
        public string isosourceabbreviation {
            get {
                return this.isosourceabbreviationField;
            }
            set {
                this.isosourceabbreviationField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("character-source-abbreviation")]
        public string charactersourceabbreviation {
            get {
                return this.charactersourceabbreviationField;
            }
            set {
                this.charactersourceabbreviationField = value;
            }
        }
        
        /// <observações/>
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <observações/>
        public string issn {
            get {
                return this.issnField;
            }
            set {
                this.issnField = value;
            }
        }
        
        /// <observações/>
        public string volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
        
        /// <observações/>
        public string issue {
            get {
                return this.issueField;
            }
            set {
                this.issueField = value;
            }
        }
        
        /// <observações/>
        public string pages {
            get {
                return this.pagesField;
            }
            set {
                this.pagesField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("pages-count")]
        public string pagescount {
            get {
                return this.pagescountField;
            }
            set {
                this.pagescountField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("reprint-address")]
        public publicationReprintAddress[] reprintaddress {
            get {
                return this.reprintaddressField;
            }
            set {
                this.reprintaddressField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("book-doi")]
        public string bookdoi {
            get {
                return this.bookdoiField;
            }
            set {
                this.bookdoiField = value;
            }
        }
        
        /// <observações/>
        public string coden {
            get {
                return this.codenField;
            }
            set {
                this.codenField = value;
            }
        }
        
        /// <observações/>
        public publicationPublisher publisher {
            get {
                return this.publisherField;
            }
            set {
                this.publisherField = value;
            }
        }
        
        /// <observações/>
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("email")]
        public string[] email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <observações/>
        public publicationConference conference {
            get {
                return this.conferenceField;
            }
            set {
                this.conferenceField = value;
            }
        }
        
        /// <observações/>
        public string isbn {
            get {
                return this.isbnField;
            }
            set {
                this.isbnField = value;
            }
        }
        
        /// <observações/>
        public string eisbn {
            get {
                return this.eisbnField;
            }
            set {
                this.eisbnField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("part-number")]
        public string partnumber {
            get {
                return this.partnumberField;
            }
            set {
                this.partnumberField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("book-group-author")]
        public string bookgroupauthor {
            get {
                return this.bookgroupauthorField;
            }
            set {
                this.bookgroupauthorField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("book-series-title")]
        public string bookseriestitle {
            get {
                return this.bookseriestitleField;
            }
            set {
                this.bookseriestitleField = value;
            }
        }
        
        /// <observações/>
        public string supplement {
            get {
                return this.supplementField;
            }
            set {
                this.supplementField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("meeting-abstract-number")]
        public string meetingabstractnumber {
            get {
                return this.meetingabstractnumberField;
            }
            set {
                this.meetingabstractnumberField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("group-author")]
        public string[] groupauthor {
            get {
                return this.groupauthorField;
            }
            set {
                this.groupauthorField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("special-issue")]
        public string specialissue {
            get {
                return this.specialissueField;
            }
            set {
                this.specialissueField = value;
            }
        }
        
        /// <observações/>
        public string eissn {
            get {
                return this.eissnField;
            }
            set {
                this.eissnField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("article-number")]
        public string articlenumber {
            get {
                return this.articlenumberField;
            }
            set {
                this.articlenumberField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("book-editor")]
        public publicationAuthor[] bookeditor {
            get {
                return this.bookeditorField;
            }
            set {
                this.bookeditorField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("keyword")]
        public string[] keyword {
            get {
                return this.keywordField;
            }
            set {
                this.keywordField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("field")]
        public string[] field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("affiliation")]
        public publicationAffiliation[] affiliation {
            get {
                return this.affiliationField;
            }
            set {
                this.affiliationField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("times-cited")]
        public publicationTimesCited[] timescited {
            get {
                return this.timescitedField;
            }
            set {
                this.timescitedField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("external-identifier")]
        public publicationExternalIdentifier[] externalidentifier {
            get {
                return this.externalidentifierField;
            }
            set {
                this.externalidentifierField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("metadata-source")]
        public publicationMetadataSource[] metadatasource {
            get {
                return this.metadatasourceField;
            }
            set {
                this.metadatasourceField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute("modified-time", DataType="nonNegativeInteger")]
        public string modifiedtime {
            get {
                return this.modifiedtimeField;
            }
            set {
                this.modifiedtimeField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.authenticus.pt/api/v2.0")]
    public partial class publicationType {
        
        private publicationTypeType typeField;
        
        private string valueField;
        
        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public publicationTypeType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.authenticus.pt/api/v2.0")]
    public enum publicationTypeType {
        
        /// <observações/>
        authenticus,
        
        /// <observações/>
        crossref,
        
        /// <observações/>
        dblp,
        
        /// <observações/>
        scopus,
        
        /// <observações/>
        wos,
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.authenticus.pt/api/v2.0")]
    public partial class paging {
        
        private object itemField;
        
        private string limitField;
        
        private apiLocation nextField;
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("cursors", typeof(pagingCursors))]
        [System.Xml.Serialization.XmlElementAttribute("timestamps", typeof(pagingTimestamps))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
            }
        }
        
        /// <observações/>
        public apiLocation next {
            get {
                return this.nextField;
            }
            set {
                this.nextField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.authenticus.pt/api/v2.0")]
    public partial class pagingCursors {
        
        private string afterField;
        
        /// <observações/>
        public string after {
            get {
                return this.afterField;
            }
            set {
                this.afterField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.authenticus.pt/api/v2.0")]
    public partial class pagingTimestamps {
        
        private decimal sinceField;
        
        /// <observações/>
        public decimal since {
            get {
                return this.sinceField;
            }
            set {
                this.sinceField = value;
            }
        }
    }

    /// <observações/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resource))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(filteredResource))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.authenticus.pt/api/v2.0")]
    public partial class apiLocation {
        
        private string locationField;
        
        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }

    /// <observações/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(filteredResource))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.authenticus.pt/api/v2.0")]
    public partial class resource : apiLocation {
        
        private resourceType typeField;
        
        private string idField;
        
        private string modifiedtimeField;
        
        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public resourceType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute("modified-time", DataType="nonNegativeInteger")]
        public string modifiedtime {
            get {
                return this.modifiedtimeField;
            }
            set {
                this.modifiedtimeField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.authenticus.pt/api/v2.0")]
    public enum resourceType {
        
        /// <observações/>
        publication,
        
        /// <observações/>
        researcher,
        
        /// <observações/>
        journal,
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.authenticus.pt/api/v2.0")]
    public partial class filteredResource : resource {
        
        private object[] filteredrelationshipsField;
        
        /// <observações/>
        [System.Xml.Serialization.XmlArrayAttribute("filtered-relationships")]
        [System.Xml.Serialization.XmlArrayItemAttribute("publication-researcher", typeof(filteredPublicationResearcher), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("researcher-institution", typeof(filteredResearcherInstitution), IsNullable=false)]
        public object[] filteredrelationships {
            get {
                return this.filteredrelationshipsField;
            }
            set {
                this.filteredrelationshipsField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.authenticus.pt/api/v2.0")]
    public partial class filteredPublicationResearcher {
        
        private string authorindexField;
        
        private string authornameField;
        
        private string researcheridField;
        
        private string modifiedtimeField;
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("author-index", DataType="nonNegativeInteger")]
        public string authorindex {
            get {
                return this.authorindexField;
            }
            set {
                this.authorindexField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("author-name")]
        public string authorname {
            get {
                return this.authornameField;
            }
            set {
                this.authornameField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("researcher-id")]
        public string researcherid {
            get {
                return this.researcheridField;
            }
            set {
                this.researcheridField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute("modified-time", DataType="nonNegativeInteger")]
        public string modifiedtime {
            get {
                return this.modifiedtimeField;
            }
            set {
                this.modifiedtimeField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.authenticus.pt/api/v2.0")]
    public partial class filteredResearcherInstitution {
        
        private string institutionidField;
        
        private string subinstitutionidField;
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("institution-id")]
        public string institutionid {
            get {
                return this.institutionidField;
            }
            set {
                this.institutionidField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("sub-institution-id")]
        public string subinstitutionid {
            get {
                return this.subinstitutionidField;
            }
            set {
                this.subinstitutionidField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.authenticus.pt/api/v2.0")]
    public partial class publicationExternalIdentifier {
        
        private publicationExternalIdentifierType typeField;
        
        private string valueField;
        
        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public publicationExternalIdentifierType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.authenticus.pt/api/v2.0")]
    public enum publicationExternalIdentifierType {
        
        /// <observações/>
        arxiv,
        
        /// <observações/>
        crossref,
        
        /// <observações/>
        dblp,
        
        /// <observações/>
        pubmed,
        
        /// <observações/>
        scopus,
        
        /// <observações/>
        wos,
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.authenticus.pt/api/v2.0")]
    public partial class publicationTimesCited {
        
        private publicationTimesCitedType typeField;
        
        private string lastupdateField;
        
        private string citationslisturlField;
        
        private string valueField;
        
        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public publicationTimesCitedType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute("last-update", DataType="nonNegativeInteger")]
        public string lastupdate {
            get {
                return this.lastupdateField;
            }
            set {
                this.lastupdateField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute("citations-list-url", DataType="anyURI")]
        public string citationslisturl {
            get {
                return this.citationslisturlField;
            }
            set {
                this.citationslisturlField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="nonNegativeInteger")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.authenticus.pt/api/v2.0")]
    public enum publicationTimesCitedType {
        
        /// <observações/>
        scopus,
        
        /// <observações/>
        wos,
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.authenticus.pt/api/v2.0")]
    public partial class publicationAffiliation {
        
        private publicationAffiliationType typeField;
        
        private string valueField;
        
        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public publicationAffiliationType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.authenticus.pt/api/v2.0")]
    public enum publicationAffiliationType {
        
        /// <observações/>
        crossref,
        
        /// <observações/>
        scopus,
        
        /// <observações/>
        wos,
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.authenticus.pt/api/v2.0")]
    public partial class publicationReprintAddress {
        
        private publicationReprintAddressType typeField;
        
        private string valueField;
        
        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public publicationReprintAddressType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.authenticus.pt/api/v2.0")]
    public enum publicationReprintAddressType {
        
        /// <observações/>
        scopus,
        
        /// <observações/>
        wos,
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.authenticus.pt/api/v2.0")]
    public partial class publicationAuthor {
        
        private string nameField;
        
        private string fullnameField;
        
        private string[] initialField;
        
        private string[] surnameField;
        
        private string[] givennameField;
        
        private string[] suffixField;
        
        private string emailField;
        
        /// <observações/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("full-name")]
        public string fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("initial")]
        public string[] initial {
            get {
                return this.initialField;
            }
            set {
                this.initialField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("surname")]
        public string[] surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("given-name")]
        public string[] givenname {
            get {
                return this.givennameField;
            }
            set {
                this.givennameField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("suffix")]
        public string[] suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }
        
        /// <observações/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.authenticus.pt/api/v2.0", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <observações/>
        author,
        
        /// <observações/>
        editor,
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.authenticus.pt/api/v2.0")]
    public partial class publicationPublisher {
        
        private string nameField;
        
        private string cityField;
        
        private string addressField;
        
        /// <observações/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <observações/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <observações/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.authenticus.pt/api/v2.0")]
    public partial class publicationConference {
        
        private string titleField;
        
        private string dateField;
        
        private string locationField;
        
        private string hostField;
        
        private string[] sponsorField;
        
        /// <observações/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <observações/>
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <observações/>
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <observações/>
        public string host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("sponsor")]
        public string[] sponsor {
            get {
                return this.sponsorField;
            }
            set {
                this.sponsorField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.authenticus.pt/api/v2.0")]
    public enum publicationMetadataSource {
        
        /// <observações/>
        authenticus,
        
        /// <observações/>
        crossref,
        
        /// <observações/>
        dblp,
        
        /// <observações/>
        scopus,
        
        /// <observações/>
        wos,
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.authenticus.pt/api/v2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.authenticus.pt/api/v2.0", IsNullable=false)]
    public partial class items {
        
        private filteredResource[] resourceField;
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("resource")]
        public filteredResource[] resource {
            get {
                return this.resourceField;
            }
            set {
                this.resourceField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.authenticus.pt/api/v2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.authenticus.pt/api/v2.0", IsNullable=false)]
    public partial class page {
        
        private filteredResource[] itemsField;
        
        private paging pagingField;
        
        /// <observações/>
        [System.Xml.Serialization.XmlArrayItemAttribute("resource", IsNullable=false)]
        public filteredResource[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <observações/>
        public paging paging {
            get {
                return this.pagingField;
            }
            set {
                this.pagingField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.authenticus.pt/api/v2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.authenticus.pt/api/v2.0", IsNullable=false)]
    public partial class researcher {
        
        private researcherExternalid[] externalidField;
        
        private string idField;
        
        private string publications2validateField;
        
        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("external-id")]
        public researcherExternalid[] externalid {
            get {
                return this.externalidField;
            }
            set {
                this.externalidField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string publications2validate {
            get {
                return this.publications2validateField;
            }
            set {
                this.publications2validateField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.authenticus.pt/api/v2.0")]
    public partial class researcherExternalid {
        
        private researcherExternalidType typeField;
        
        private string valueField;
        
        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public researcherExternalidType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <observações/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.authenticus.pt/api/v2.0")]
    public enum researcherExternalidType {
        
        /// <observações/>
        orcid,
        
        /// <observações/>
        [System.Xml.Serialization.XmlEnumAttribute("researcher-id")]
        researcherid,
        
        /// <observações/>
        [System.Xml.Serialization.XmlEnumAttribute("google-scholar")]
        googlescholar,
        
        /// <observações/>
        [System.Xml.Serialization.XmlEnumAttribute("scopus-author-id")]
        scopusauthorid,
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.authenticus.pt/api/v2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.authenticus.pt/api/v2.0", IsNullable=false)]
    public partial class error {
        
        private string descriptionField;
        
        /// <observações/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
}